### ISSUE TITLE
Hugo move tracking issue

### ISSUE THREAD

**Issue by VoyTechnology** [cpssd-students/cpssd.net#34]
There are several steps I will now take to ensure the move to hugo is smooth as possible:

- [ ] Merge the PR #30 
- [ ] Enable `cpssd-students` in CircleCI so the site can be built and deployed
- [ ] Be "on-call" for any breakage caused by the merge or any issues

Please put any comments regarding problems caused by move to hugo in this issue, or make a new one and reference this one.

**Comment by VoyTechnology** [comment]
First build deployed, some CSS issues. I am looking into them now.

**Comment by VoyTechnology** [comment]
There were a bunch of old files left over from the previous version of `gh-pages`. I manually removed the branch and created a new one. Will probably have to automate the process soon.

**Comment by VoyTechnology** [comment]
@iandioch CircleCI is already used to actually deploy. But yea, just an additional `rm -r` before moving the new files in.
